### ISSUE TITLE
Thanos 0.20

### ISSUE THREAD

**Issue by ethernoy** [bitnami/bitnami-docker-thanos#4]
Thanos v0.20 has been released. I wonder will Bitnami create a Bitnami Thanos image for this version as well? https://hub.docker.com/r/bitnami/thanos/tags?page=1&ordering=last_updated seems to be outdated for a month.

**Comment by migruiz4** [comment]
Hi @ethernoy,

Yes, our team is currently working on updating the Thanos image to its latest version 0.20.

This last update didn't pass our tests, so we are working on the necessary changes so the Thanos image and chart for v0.20 are released working as expected.

I'm sorry for the inconvenience, I will let you know as soon as it is available.

**Comment by migruiz4** [comment]
I'm moving this to 'on-hold' to prevent stale-bot from coming around.

I'm sorry this is taking longer than expected.

**Comment by fmulero** [comment]
`bitnami/thanos:0.20.1` was released several months ago. We can close this issue
